import { Injectable } from '@nestjs/common';
import { Prisma, ChannelMemberRole, ChannelStatus, CredentialProvider, UserStatus } from '@atmp/database';
import { PrismaService } from '../../../infrastructure/prisma/prisma.service';
import { AppError } from '@atmp/shared';
import type { AddMemberDto, CreateChannelDto, CredentialRefDto, UpdateChannelDto, UpdateSettingsDto } from '../presentation/dto/channel.dto';
const rank: Record<ChannelMemberRole,number> = { OWNER:4, EDITOR:3, OPERATOR:2, VIEWER:1 };
@Injectable() export class ChannelsService {
  constructor(private readonly prisma: PrismaService) {}
  async create(actorId:string,dto:CreateChannelDto){ const u=await this.prisma.user.findUnique({where:{id:actorId}}); if(!u||u.status!==UserStatus.ACTIVE) throw new AppError('UNAUTHORIZED','Active actor required'); return this.prisma.$transaction(async tx=>{ const c=await tx.channel.create({data:{telegramId:dto.telegramId,username:dto.username,title:dto.title,language:dto.language??'en',createdById:actorId,settings:{create:{}},members:{create:{userId:actorId,role:ChannelMemberRole.OWNER}}},include:{settings:true}}); await tx.auditLog.create({data:{actorType:'HUMAN',actorId,action:'channel.created',entityType:'Channel',entityId:c.id}}); return c; }); }
  async list(actorId:string){ await this.user(actorId); return this.prisma.channel.findMany({where:{members:{some:{userId:actorId}},status:{not:ChannelStatus.ARCHIVED}},include:{settings:true,members:{where:{userId:actorId},select:{role:true}}},orderBy:{createdAt:'desc'}}); }
  async get(actorId:string,id:string){ await this.role(actorId,id,ChannelMemberRole.VIEWER); return this.prisma.channel.findUniqueOrThrow({where:{id},include:{settings:true,members:{include:{user:{select:{id:true,email:true,displayName:true,status:true}}}},credential:{select:{id:true,provider:true,secretRef:true,updatedAt:true}}}}); }
  async update(actorId:string,id:string,dto:UpdateChannelDto){ await this.role(actorId,id,ChannelMemberRole.EDITOR); const c=await this.prisma.channel.update({where:{id},data:dto as Prisma.ChannelUpdateInput}); await this.audit(actorId,'channel.updated','Channel',id,dto as unknown as Prisma.InputJsonValue); return c; }
  async updateSettings(actorId:string,id:string,dto:UpdateSettingsDto){ await this.role(actorId,id,ChannelMemberRole.OWNER); const current=await this.prisma.channelSettings.findUnique({where:{channelId:id}}); if(!current) throw new AppError('NOT_FOUND','Channel settings not found'); if(current.version!==dto.expectedVersion) throw new AppError('CONFLICT','Settings version is stale',{expectedVersion:current.version}); const {expectedVersion:_v,...changes}=dto; if(changes.minLength!==undefined&&changes.maxLength!==undefined&&changes.minLength>changes.maxLength) throw new AppError('VALIDATION','minLength cannot exceed maxLength'); const s=await this.prisma.channelSettings.update({where:{channelId:id},data:{...changes,version:{increment:1},forbiddenTopics:changes.forbiddenTopics as Prisma.InputJsonValue,legalRestrictions:changes.legalRestrictions as Prisma.InputJsonValue,sourcePriorities:changes.sourcePriorities as Prisma.InputJsonValue,styleConfig:changes.styleConfig as Prisma.InputJsonValue}}); await this.audit(actorId,'channel.settings.updated','ChannelSettings',s.id,{expectedVersion:dto.expectedVersion,newVersion:s.version}); return s; }
  async addMember(actorId:string,id:string,dto:AddMemberDto){ await this.role(actorId,id,ChannelMemberRole.OWNER); const u=await this.prisma.user.findUnique({where:{id:dto.userId}}); if(!u||u.status!==UserStatus.ACTIVE) throw new AppError('NOT_FOUND','Active user not found'); const m=await this.prisma.channelMember.upsert({where:{channelId_userId:{channelId:id,userId:dto.userId}},create:{channelId:id,userId:dto.userId,role:dto.role},update:{role:dto.role}}); await this.audit(actorId,'channel.member.upserted','ChannelMember',m.id,{userId:dto.userId,role:dto.role}); return m; }
  async setCredential(actorId:string,id:string,dto:CredentialRefDto){ await this.role(actorId,id,ChannelMemberRole.OWNER); const r=await this.prisma.sourceCredentialRef.upsert({where:{channelId:id},create:{channelId:id,provider:CredentialProvider.TELEGRAM_BOT,secretRef:dto.secretRef,createdById:actorId},update:{secretRef:dto.secretRef}}); await this.audit(actorId,'channel.credential_ref.updated','SourceCredentialRef',r.id,{provider:r.provider}); return {id:r.id,provider:r.provider,secretRef:r.secretRef,updatedAt:r.updatedAt}; }
  private async user(id:string){ const u=await this.prisma.user.findUnique({where:{id}}); if(!u||u.status!==UserStatus.ACTIVE) throw new AppError('UNAUTHORIZED','Active actor required'); return u; }
  private async role(uid:string,cid:string,min:ChannelMemberRole){ await this.user(uid); const m=await this.prisma.channelMember.findUnique({where:{channelId_userId:{channelId:cid,userId:uid}}}); if(!m||rank[m.role]<rank[min]) throw new AppError('FORBIDDEN','Insufficient channel role'); return m; }
  private async audit(actorId:string,action:string,type:string,id:string,metadata?:Prisma.InputJsonValue){ await this.prisma.auditLog.create({data:{actorType:'HUMAN',actorId,action,entityType:type,entityId:id,metadata}}); }
}
