'use client';

import { channelResponseSchema, sourceResponseSchema, type SourceResponse } from '@atmp/contracts';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { apiGet, apiMutate } from '@/lib/api';

const sourceListSchema = sourceResponseSchema.array();
const channelsSchema = channelResponseSchema.array();
const actionSchema = sourceResponseSchema.partial();

function SourceCard({ channelId, source }: { channelId: string; source: SourceResponse }) {
  const queryClient = useQueryClient();
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(source.name);
  const [priority, setPriority] = useState(String(source.priority));
  const [categories, setCategories] = useState(source.categories.join(', '));
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['sources', channelId] });
  const update = useMutation({ mutationFn: () => apiMutate(`/channels/${channelId}/sources/${source.id}`, 'PATCH', { name, priority: Number(priority) || 0, categories: categories.split(',').map((value) => value.trim()).filter(Boolean) }, sourceResponseSchema), onSuccess: refresh });
  const toggle = useMutation({ mutationFn: (enabled: boolean) => apiMutate(`/channels/${channelId}/sources/${source.id}`, 'PATCH', { enabled }, sourceResponseSchema), onSuccess: refresh });
  const ingest = useMutation({ mutationFn: () => apiMutate(`/channels/${channelId}/sources/${source.id}/ingest`, 'POST', {}, actionSchema) });
  const health = useMutation({ mutationFn: () => apiGet(`/channels/${channelId}/sources/${source.id}/health`, actionSchema) });
  return <article className="rounded-md border border-border/70 bg-slate-950/20 p-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0">{editing ? <input className="w-full rounded border border-border bg-slate-900 px-2 py-1 text-sm text-slate-200" value={name} onChange={(event) => setName(event.target.value)} /> : <h3 className="font-medium text-slate-200">{source.name}</h3>}<p className="mt-1 truncate text-xs text-slate-500">{source.type} · {source.url}</p></div><span className={`rounded px-2 py-0.5 text-xs ${source.enabled ? 'bg-emerald-500/15 text-emerald-300' : 'bg-slate-500/15 text-slate-400'}`}>{source.enabled ? 'enabled' : 'disabled'}</span></div>{editing ? <div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-xs text-slate-500">Priority<input className="mt-1 w-full rounded border border-border bg-slate-900 px-2 py-1 text-sm text-slate-200" value={priority} onChange={(event) => setPriority(event.target.value)} /></label><label className="text-xs text-slate-500">Categories<input className="mt-1 w-full rounded border border-border bg-slate-900 px-2 py-1 text-sm text-slate-200" value={categories} onChange={(event) => setCategories(event.target.value)} /></label></div> : <div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500"><span>priority {source.priority}</span>{source.categories.map((category) => <span key={category} className="rounded bg-slate-800 px-2 py-0.5">{category}</span>)}</div>}<div className="mt-4 flex flex-wrap gap-2">{editing ? <><button className="rounded bg-indigo-500 px-2 py-1 text-xs text-white disabled:opacity-50" disabled={update.isPending} onClick={() => update.mutate()}>Save</button><button className="rounded border border-border px-2 py-1 text-xs text-slate-300" onClick={() => setEditing(false)}>Cancel</button></> : <button className="rounded border border-border px-2 py-1 text-xs text-slate-300" onClick={() => setEditing(true)}>Edit</button>}<button className="rounded border border-border px-2 py-1 text-xs text-slate-300" onClick={() => toggle.mutate(!source.enabled)}>{source.enabled ? 'Disable' : 'Enable'}</button><button className="rounded border border-border px-2 py-1 text-xs text-slate-300" onClick={() => health.mutate()}>Health</button><button className="rounded border border-border px-2 py-1 text-xs text-slate-300" onClick={() => ingest.mutate()}>Ingest</button></div><p className="mt-3 text-xs text-slate-500">{source.lastHealthStatus ?? 'not checked'} · {source.lastIngestedAt ? `last ingested ${new Date(source.lastIngestedAt).toLocaleString()}` : 'not ingested'}</p>{(update.isError || toggle.isError || ingest.isError || health.isError) && <p className="mt-2 text-xs text-rose-300">Action failed. Check the API and try again.</p>}{health.isSuccess && <p className="mt-2 text-xs text-emerald-300">Health probe completed.</p>}</article>;
}

export function SourcesPanel() {
  const queryClient = useQueryClient();
  const channels = useQuery({ queryKey: ['channels'], queryFn: () => apiGet('/channels', channelsSchema) });
  const channelId = channels.data?.[0]?.id;
  const sources = useQuery({ queryKey: ['sources', channelId], enabled: Boolean(channelId), queryFn: () => apiGet(`/channels/${channelId}/sources`, sourceListSchema) });
  const [form, setForm] = useState({ name: '', type: 'RSS' as 'RSS' | 'WEB', url: '', priority: '0', categories: '' });
  const create = useMutation({ mutationFn: () => apiMutate(`/channels/${channelId}/sources`, 'POST', { ...form, priority: Number(form.priority) || 0, categories: form.categories.split(',').map((value) => value.trim()).filter(Boolean) }, sourceResponseSchema), onSuccess: () => { setForm({ name: '', type: 'RSS', url: '', priority: '0', categories: '' }); queryClient.invalidateQueries({ queryKey: ['sources', channelId] }); } });
  const ingestAll = useMutation({ mutationFn: () => apiMutate(`/channels/${channelId}/sources/ingest`, 'POST', {}, sourceListSchema) });
  return <section className="rounded-lg border border-border bg-panel p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-medium text-slate-300">Sources</h2><p className="mt-1 text-xs text-slate-500">RSS and web inputs, health, priority and ingestion state.</p></div><button disabled={!channelId || ingestAll.isPending} onClick={() => ingestAll.mutate()} className="rounded bg-indigo-500 px-3 py-1.5 text-xs text-white disabled:opacity-50">Ingest all</button></div>{!channelId && <p className="mt-4 text-sm text-slate-500">Create a channel first.</p>}{channelId && <><form className="mt-4 grid gap-2 rounded border border-border/70 p-3 md:grid-cols-5" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><input required placeholder="Name" className="rounded border border-border bg-slate-900 px-2 py-1 text-sm text-slate-200" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><select className="rounded border border-border bg-slate-900 px-2 py-1 text-sm text-slate-200" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as 'RSS' | 'WEB' })}><option value="RSS">RSS</option><option value="WEB">Web</option></select><input required type="url" placeholder="https://..." className="rounded border border-border bg-slate-900 px-2 py-1 text-sm text-slate-200 md:col-span-2" value={form.url} onChange={(event) => setForm({ ...form, url: event.target.value })} /><button disabled={create.isPending} className="rounded bg-emerald-500 px-3 py-1 text-xs text-slate-950 disabled:opacity-50">Add source</button></form>{sources.isPending && <p className="mt-4 text-sm text-slate-500">Loading sources...</p>}{sources.isError && <p className="mt-4 text-sm text-rose-300">Source API unavailable.</p>}<div className="mt-4 grid gap-3 lg:grid-cols-2">{sources.data?.map((source) => <SourceCard key={source.id} channelId={channelId} source={source} />)}</div>{sources.data?.length === 0 && <p className="mt-4 text-sm text-slate-500">No sources yet.</p>}</>}</section>;
}
